GRAPH_BASELINE_MATCH_PROMPT = (
    "You are scoring how well a baseline paper matches the idea context. "
    "Use the candidate node fields (keywords/problem/innovation/scenarios) and the idea card. "
    "Score each dimension from 0-5, then compute a weighted score and return JSON only.\n"
    "\n"
    "Dimensions (0-5 each):\n"
    "1) task_alignment: Does the candidate address the same task/domain as the idea?\n"
    "2) problem_alignment: Does the candidate target the same core problem or limitation?\n"
    "3) method_alignment: Are the method family / technical approach aligned?\n"
    "4) innovation_overlap: Do the innovations/key components overlap with the idea?\n"
    "5) scenario_alignment: Do the scenarios/benchmarks/setting overlap?\n"
    "6) baseline_fit: Is the candidate a sensible baseline to compare against for this idea?\n"
    "\n"
    "Weights (must use exactly):\n"
    "task_alignment=0.20, problem_alignment=0.20, method_alignment=0.20, "
    "innovation_overlap=0.15, scenario_alignment=0.15, baseline_fit=0.10\n"
    "\n"
    "Compute:\n"
    "weighted_score = sum(subscore * weight)  (subscores are 0-5)\n"
    "match_score = round(weighted_score / 5 * 100, 1)\n"
    "\n"
    "Return JSON only with keys:\n"
    "{{\n"
    "  \"subscores\": {{\n"
    "    \"task_alignment\": <0-5>,\n"
    "    \"problem_alignment\": <0-5>,\n"
    "    \"method_alignment\": <0-5>,\n"
    "    \"innovation_overlap\": <0-5>,\n"
    "    \"scenario_alignment\": <0-5>,\n"
    "    \"baseline_fit\": <0-5>\n"
    "  }},\n"
    "  \"weighted_score\": <0-5>,\n"
    "  \"match_score\": <0-100>\n"
    "}}\n"
    "\n"
    "IdeaCard:\n"
    "{idea_card}\n"
    "NodeFields:\n"
    "{node_fields}\n"
)
